#!/usr/bin/env python3

from collections.abc import Iterable

class SubConfig():
  defaults = None
  baseKey = None
  requiredVariables = {}
  optionalVariables = {}
  variablesWithDefaults = {}
  def __init__(self, config):
    self.logPrefix = self.__class__.__name__+': '

    #######################
    # renew config defaults
    #######################
    config.renew(self.defaults, self.baseKey)
    self.__config = config
    self._vtable = {}

    ##############
    # parse config
    ##############
    for v, t in self.requiredVariables.items():
      self._setOrDie(v, t)

    for v, t in self.optionalVariables.items():
      self._setOrNone(v, t)

    for v, a in self.variablesWithDefaults.items():
      self._setOrDefault(v, a[0], a[1])

  def exportTasks(self, text):
    self.write('include/tasks/auto/'+self.baseKey+'.rc', text)

  def exportVarsToCsh(self, variables):
    Str = ['''#!/bin/csh -f
######################################################
# THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY.
# MODIFY THE SCENARIO YAML FILE INSTEAD.
######################################################

if ( $?config_'''+self.baseKey+''' ) exit 0
set config_'''+self.baseKey+''' = 1

''']
    for v in variables:
      Str += self.varToCsh(v, self._vtable[v])
    self.write('config/auto/'+self.baseKey+'.csh', Str)

  def exportVarsToCylc(self, variables):
    Str = []
    for v in variables:
      Str += self.varToCylc(v, self._vtable[v])
    self.write('include/variables/auto/'+self.baseKey+'.rc', Str)

  def exportVars(self, csh=[], cylc=[]):
    #################################
    # auto-generate shell config file
    #################################
    self.exportVarsToCsh(csh)

    ##################################
    # auto-generate cylc include files
    ##################################
    self.exportVarsToCylc(cylc)

  def get(self, v):
    return self._vtable[v]

  def _set(self, v, value):
    self._vtable[v] = value

  def _setOrDie(self, v, t=None):
    self._vtable[v] = self.__config.getOrDie(v)
    if t is not None:
      self._vtable[v] = t(self._vtable[v])

  def _setOrNone(self, v, t=None):
    self._vtable[v] = self.__config.get(v)
    if self._vtable[v] is not None and t is not None:
      self._vtable[v] = t(self._vtable[v])

  def _setOrDefault(self, v, default, t=None):
    self._vtable[v] = self.__config.getOrDefault(v, default)
    if t is not None:
      self._vtable[v] = t(self._vtable[v])

  @staticmethod
  def varToCsh(var, value):
    if isinstance(value, Iterable) and not isinstance(value, str):
      vsh = str(value)
      vsh = vsh.replace('\'','')
      vsh = vsh.replace('[','')
      vsh = vsh.replace(']','')
      vsh = vsh.replace(',',' ')
      return ['set '+var+' = ('+vsh+')\n']
    else:
      return ['setenv '+var+' "'+str(value)+'"\n']

  @staticmethod
  def varToCylc(var, value):
    if isinstance(value, str):
      return ['{% set '+var+' = "'+value+'" %}\n']
    else:
      return ['{% set '+var+' = '+str(value)+' %}\n']

  @staticmethod
  def write(filename, Str):
     print('Creating '+filename)
     with open(filename, 'w') as f:
       f.writelines(Str)
       f.close()

