_state variables: &daStateVars
- water_vapor_mixing_ratio_wrt_dry_air
- cloud_liquid_water
- rain_water
- cloud_liquid_ice
- snow_water
- graupel
- cloud_ice_number_concentration
- rain_number_concentration
- cloud_droplet_number_concentration
- u
- w
- dry_air_density
- pressure_p
- air_potential_temperature
- relative_humidity
- eastward_wind
- northward_wind
- air_pressure_at_surface
- cldfrac
- re_cloud
- re_ice
- re_snow
- refl10cm
- refl10cm_max
- rainc
- rainnc
- lai
- sfc_albedo
- mavail
- sfc_emiss
- thc
- ust
- z0
- znt
- skin_temperature_at_surface
- snow
- snowc
- snowh
- sst
- tmn
- vegetation_area_fraction
- seaice
- seaice_fraction
- eastward_wind_at_10m
- northward_wind_at_10m
- water_vapor_mixing_ratio_wrt_moist_air_at_2m
- air_temperature_at_2m
- precipw
- sh2o
- smois
- tslb

# The following variables from the da_stream are not recentered:
# 1) static variables (terrain, hydrostatic balances):
#- ter
#- xland
#- dzs
#- zs
#- pressure_base
#- rho_base
#- theta_base
#
# 2) real-valued variables that are identical across ensemble members:
#- sfc_albbck
#- sfc_emibck
#
# 3) scalar integer variables identical across ensemble members
#    (a real-valued mean would not be meaningful)
#- isice_lu
#- iswater_lu
#
# 4) variables containing information about past states
#- xicem
#- h_oml_initial
#
# 5) redundant variables
#- air_pressure  (note: wa already recentered pressure_p)

_current date: &currentDate {{cycleDateISO8601}}  #2018-04-15T06:00:00Z

recenter variables: *daStateVars

center geometry:
  nml_file: {{namelistFileCenter}}  # ./data/120km/namelist.atmosphere_120km
  streams_file: {{streamsFileCenter}}  # ./data/120km/streams.atmosphere_120km
  deallocate non-da fields: false

center:
  #filename: /glade/u/home/stoedtli/scratch/pandac/stoedtli_3denvar_120km_uncoupled_1/CyclingDA/2018041506/an/an.$Y-$M-$D_$h.$m.$s.nc
  filename: {{analysisFileCenter}}  # ./data/c5/ens_mean.$Y-$M-$D_$h.$m.$s.nc
  date: *currentDate
  state variables: *daStateVars
  stream name: da_state
  transform model to analysis: false

#center output:
  #filename: ./data/c5/center.$Y-$M-$D_$h.$m.$s.nc
  #stream name: da_state

ensemble geometry:
  nml_file: {{namelistFileEnsemble}}  # ./data/120km/namelist.atmosphere_120km
  streams_file: {{streamsFileEnsemble}}  # ./data/120km/streams.atmosphere_120km
  deallocate non-da fields: false

ensemble:
  members from template:
    template:
      date: *currentDate
      state variables: *daStateVars
      #filename: /glade/u/home/stoedtli/scratch/pandac/stoedtli_getkf_120km_20mem_uncoupled_1/CyclingDA/2018041506/an/mem%iMember%/an.$Y-$M-$D_$h.$m.$s.nc
      filename: {{analysisFileEnsemble}} # /glade/u/home/stoedtli/scratch/pandac/stoedtli_getkf_120km_20mem_uncoupled_1/CyclingDA/2018041506/an/mem%iMember%/an.$Y-$M-$D_$h.$m.$s.nc
      stream name: da_state
      transform model to analysis: false
    pattern: %iMember%
    start: 1
    zero padding: {{paddingEnsembleMembers}}
    nmembers: {{numberEnsembleMembers}}

#ensemble meanoutput:
  #filename: ./data/c5/mean.$Y-$M-$D_$h.$m.$s.nc
  #stream name: da_state

recentered output:
  filename: {{analysisFileRecenter}}  #./data/c5/mem%{member}%_recentered.$Y-$M-$D_$h.$m.$s.nc
  stream name: da_state

