- obs space:
    <<: *ObsSpace
    name: amsua_metop-a
    _obsdatain: &ObsDataIn
      engine:
        type: H5File
        obsfile: {{InDBDir}}/amsua_metop-a_rttov_obs_{{thisValidDate}}.h5
    _obsdataout: &ObsDataOut
      engine:
        type: H5File
        obsfile: {{OutDBDir}}{{MemberDir}}/{{obsPrefix}}_amsua_metop-a{{ObsOutSuffix}}.h5
    obsdatain: *{{ObsDataIn}}
    {{ObsDataOut}}
    simulated variables: [brightnessTemperature]
    channels: &amsua_metop-a_channels 1-15
  obs error: *ObsErrorDiagonal
  <<: *horizObsLoc
  obs operator:
    name: RTTOVCPP
    CoefPath: /glade/work/liuz/rttov14/rtcoef_rttov14/rttov13pred54L/
    SensorID: metop_2_amsua_o3
