  obs filters:
  - filter: GOMsaver
    filename: {{OutDBDir}}{{MemberDir}}/{{geoPrefix}}_amsua-cld_n19.nc4
  - filter: Domain Check
    where:
    - variable:
        name: MetaData/sensorZenithAngle
      maxvalue: 45.0

  - filter: Background Check
    threshold: 3.0
    <<: *multiIterationFilter
  - filter: BlackList
    filter variables:
    - name: brightnessTemperature
      channels: 1-4,15
    action:
      name: assign error
      error function:
        name: ObsFunction/ObsErrorModelRamp
        channels: 1-4,15
        options:
          channels: 1-4,15
          xvar:
            name: ObsFunction/CLWRetSymmetricMW
            options:
              clwret_ch238: 1
              clwret_ch314: 2
              clwret_types: [ObsValue, HofX]
              bias_application: ObsValue
          x0:    [  0.03,  0.03,  0.03,  0.03, 0.03]
          x1:    [  0.59,  0.59,  0.38,  0.47, 0.26]
          err0:  [  4.31,  3.19,  2.31,  0.65, 5.57]
          err1:  [ 32.39, 44.42, 14.54,  3.02, 16.15]
    <<: *multiIterationFilter
  - filter: Gaussian_Thinning
    horizontal_mesh: {{RADTHINDISTANCE}}
  - filter: Domain Check
    filter variables:
    - name: brightnessTemperature
      channels: 1-4,15
    where:
    - variable:
        name: GeoVaLs/water_area_fraction
      minvalue: 1.0
    <<: *multiIterationFilter
