  obs filters:
  - filter: Gaussian_Thinning
    horizontal_mesh: {{RADTHINDISTANCE}}
    action:
      name: reduce obs space

  - filter: Domain Check
    where:
    - variable:
        name: MetaData/sensorZenithAngle
      maxvalue: 45.0

  - filter: BlackList
    filter variables:
    - name: brightnessTemperature
      channels: 1-15
    action:
      name: assign error
      error function:
        name: ObsFunction/ObsErrorModelRamp
        channels: 1-15
        options:
          channels: 1-15
          xvar:
            name: ObsFunction/CLWRetSymmetricMW
            options:
              clwret_ch238: 1
              clwret_ch314: 2
              clwret_types: [ObsValue, HofX]
              #bias_application: ObsValue
          x0: &id1metopAamsua
            [0.03,  0.03,  0.03,  0.03,  0.0,
             0.1,   0.0,   0.0,   0.0,   0.0,
             0.0,   0.0,   0.0,   0.0,   0.03]
          x1: &id2metopAamsua
            [0.55,  0.58,  0.37,  0.44,  1.0,
             1.50,  0.0,   0.0,   0.0,   0.0,
             0.0,   0.0,   0.0,   0.0,   0.23]
          err0: &id3metopAamsua
            [4.41, 3.22, 2.51,  0.59,  0.3,
             0.23, 0.23, 0.25,  0.25,  0.35,
             0.4,  0.55, 0.8,   4.0,   5.60]
          err1: &id4metopAamsua
            [31.20, 43.6, 14.12, 2.94,  0.5,
              0.3,  0.23, 0.25,  0.25,  0.35,
              0.4,  0.55, 0.8,   4.0,  15.36]
    <<: *multiIterationFilter

# partly address cold-air outbreak issues
  - filter: Domain Check
    filter variables:
    - name: brightnessTemperature
      channels: 1-4,15
    where:
    - variable:
        name: GeoVaLs/water_area_fraction
      minvalue: 1.0
    - variable:
        name: MetaData/latitude
      minvalue: -60.0
      maxvalue: 60.0
    <<: *multiIterationFilter

#  Obs CLW Retrieval Check
  - filter: Bounds Check
    filter variables:
    - name: brightnessTemperature
      channels: 1-6, 15
    test variables:
    - name: ObsFunction/CLWRetMW
      options:
        clwret_ch238: 1
        clwret_ch314: 2
        clwret_types: [ObsValue]
    maxvalue: 999.0
    action:
      name: reject
    <<: *multiIterationFilter

#  Background CLW Retrieval Check
  - filter: Bounds Check
    filter variables:
    - name: brightnessTemperature
      channels: 1-6, 15
    test variables:
    - name: ObsFunction/CLWRetMW
      options:
        clwret_ch238: 1
        clwret_ch314: 2
        clwret_types: [HofX]
    maxvalue: 999.0
    action:
      name: reject
    <<: *multiIterationFilter

#  Topography check
  - filter: BlackList
    filter variables:
    - name: brightnessTemperature
      channels: 1-15
    action:
      name: inflate error
      inflation variable:
        name: ObsFunction/ObsErrorFactorTopoRad
        channels: 1-15
        options:
          sensor: microwave
          channels: 1-15
    <<: *multiIterationFilter

#  Transmittance Top Check
  - filter: BlackList
    filter variables:
    - name: brightnessTemperature
      channels: 1-15
    action:
      name: inflate error
      inflation variable:
        name: ObsFunction/ObsErrorFactorTransmitTopRad
        channels: 1-15
        options:
          channels: 1-15
    <<: *multiIterationFilter

#  Surface Jacobian check
  - filter: BlackList
    filter variables:
    - name: brightnessTemperature
      channels: 1-15
    action:
      name: inflate error
      inflation variable:
        name: ObsFunction/ObsErrorFactorSurfJacobianRad
        channels: 1-15
        options:
          channels: 1-15
          sensor: amsua_metop-a
          obserr_demisf: [0.010, 0.020, 0.015, 0.020, 0.200]
          obserr_dtempf: [0.500, 2.000, 1.000, 2.000, 4.500]
    <<: *multiIterationFilter

#  Situation dependent Check
  - filter: BlackList
    filter variables:
    - name: brightnessTemperature
      channels: 1-15
    action:
      name: inflate error
      inflation variable:
        name: ObsFunction/ObsErrorFactorSituDependMW
        channels: 1-15
        options:
          sensor: amsua_metop-a
          channels: 1-15
          clwobs_function:
            name: ObsFunction/CLWRetMW
            options:
              clwret_ch238: 1
              clwret_ch314: 2
              clwret_types: [ObsValue]
          clwbkg_function:
            name: ObsFunction/CLWRetMW
            options:
              clwret_ch238: 1
              clwret_ch314: 2
              clwret_types: [HofX]
              #bias_application: HofX
          scatobs_function:
            name: ObsFunction/SCATRetMW
            options:
              scatret_ch238: 1
              scatret_ch314: 2
              scatret_ch890: 15
              scatret_types: [ObsValue]
              #bias_application: HofX
          clwmatchidx_function:
            name: ObsFunction/CLWMatchIndexMW
            channels: 1-15
            options:
              channels: 1-15
              clwobs_function:
                name: ObsFunction/CLWRetMW
                options:
                  clwret_ch238: 1
                  clwret_ch314: 2
                  clwret_types: [ObsValue]
              clwbkg_function:
                name: ObsFunction/CLWRetMW
                options:
                  clwret_ch238: 1
                  clwret_ch314: 2
                  clwret_types: [HofX]
                  #bias_application: HofX
              clwret_clearsky: *id1metopAamsua
          obserr_function:
            name: ObsFunction/ObsErrorModelRamp
            channels: 1-15
            options:
              channels: 1-15
              xvar:
                name: ObsFunction/CLWRetSymmetricMW
                options:
                  clwret_ch238: 1
                  clwret_ch314: 2
                  clwret_types:
                  - ObsValue
                  - HofX
              x0: *id1metopAamsua
              x1: *id2metopAamsua
              err0: *id3metopAamsua
              err1: *id4metopAamsua
          obserr_clearsky: *id3metopAamsua
    <<: *multiIterationFilter

#  Gross check
  - filter: Background Check
    filter variables:
    - name: brightnessTemperature
      channels: 1-15
    function absolute threshold:
    - name: ObsFunction/ObsErrorBoundMW
      channels: 1-15
      options:
        sensor: amsua_metop-a
        channels: 1-15
        #thresholdfactor: 1
        obserr_bound_latitude:
          name: ObsFunction/ObsErrorFactorLatRad
          options:
            latitude_parameters: [25.0, 0.25, 0.04, 3.0]
        obserr_bound_transmittop:
          name: ObsFunction/ObsErrorFactorTransmitTopRad
          channels: 1-15
          options:
            channels: 1-15
        obserr_bound_topo:
          name: ObsFunction/ObsErrorFactorTopoRad
          channels: 1-15
          options:
            channels: 1-15
            sensor: microwave
        obserr_function:
          name: ObsFunction/ObsErrorModelRamp
          channels: 1-15
          options:
            channels: 1-15
            xvar:
              name: ObsFunction/CLWRetSymmetricMW
              options:
                clwret_ch238: 1
                clwret_ch314: 2
                clwret_types: [ObsValue, HofX]
                #bias_application: HofX
            x0:  *id1metopAamsua
            x1:  *id2metopAamsua
            err0: *id3metopAamsua
            err1: *id4metopAamsua
        threshold: 3
        threshold_precip: 2.5
        obserr_bound_max: [4.5, 4.5, 4.5, 2.5, 2.0,
                           2.0, 2.0, 2.0, 2.0, 2.0,
                           2.5, 3.5, 4.5, 4.5, 4.5]
    action:
      name: reject
    <<: *multiIterationFilter

#  Inter-channel check
  - filter: Bounds Check
    filter variables:
    - name: brightnessTemperature
      channels: 1-15
    test variables:
    - name: ObsFunction/InterChannelConsistencyCheck
      channels: 1-15
      options:
        channels: 1-15
        sensor: amsua_metop-a
        use_flag: &id5metopAamsua
          [1,  1,  1,  1,  1,
           1, -1, -1,  1, -1,
          -1, -1, -1, -1,  1 ]
    maxvalue: 1.0e-12
    action:
      name: reject
    <<: *multiIterationFilter

#  Useflag check
  - filter: Bounds Check
    filter variables:
    - name: brightnessTemperature
      channels: 1-15
    test variables:
    - name: ObsFunction/ChannelUseflagCheckRad
      channels: 1-15
      options:
        channels: 1-15
        use_flag: *id5metopAamsua
    minvalue: 1.0e-12
    action:
      name: reject
    <<: *multiIterationFilter

#  - filter: GOMsaver
#    filename: {{OutDBDir}}{{MemberDir}}/{{geoPrefix}}_amsua-cld_metop-a.nc4
