  obs filters:
  #- filter: GOMsaver
  #  filename: {{OutDBDir}}{{MemberDir}}/{{geoPrefix}}_mhs_metop-b.nc4
  - filter: Gaussian_Thinning
    horizontal_mesh: {{RADTHINDISTANCE}}
    action:
      name: reduce obs space

  - filter: Domain Check
    filter variables:
    - name: brightnessTemperature
      channels: 5
    where:
    - variable:
        name: MetaData/latitude
      minvalue: -60.0
      maxvalue: 60.0
    <<: *multiIterationFilter

# BennartzScatIndex check: remove excessive SI over water
  - filter: Bounds Check
    filter variables:
    - name: brightnessTemperature
      channels: 4-5
    where:
    - variable:
        name: GeoVaLs/water_area_fraction
      minvalue: 1.0
    test variables:
    - name: ObsFunction/BennartzScatIndex
      options:
        channel_89ghz: 1
        channel_150ghz: 2
        bennartz_coeff_1: -39.2010
        bennartz_coeff_2: 0.1104
        apply_bias: ObsBiasData
    maxvalue: 20.0
    action:
      name: reject
    <<: *multiIterationFilter

# obs prior filters:
# over non-water:
  - filter: BlackList
    filter variables:
    - name: brightnessTemperature
      channels: *mhs_metop-b_channels
    where:
    - variable:
        name: GeoVaLs/water_area_fraction
      maxvalue: 0.99
    action:
      name: assign error
      error function:
        name: ObsFunction/ObsErrorModelRamp
        channels: *mhs_metop-b_channels
        options:
          channels: *mhs_metop-b_channels
          xvar:
            name: ObsFunction/SIRetSymmetricMW
            options:
              siret_ch90: 1
              siret_ch150: 2
              siret_types: [ObsValue, HofX]
              bias_application: ObsValue
          x0:    [  0.08,   0.08,   0.00,   0.00,   0.00]
          x1:    [ 27.98,  29.78,  20.70,  18.30,  14.70]
          err0:  [ 500.,   500.,    2.58,   2.60,   2.52]
          err1:  [ 500.,   500.,  16.96,  23.67,  21.70]

# over water
  - filter: BlackList
    filter variables:
    - name: brightnessTemperature
      channels: *mhs_metop-b_channels
    where:
    - variable:
        name: GeoVaLs/water_area_fraction
      minvalue: 1.0
    action:
      name: assign error
      error function:
        name: ObsFunction/ObsErrorModelQuad
        channels: *mhs_metop-b_channels
        options:
          channels: *mhs_metop-b_channels
          xvar:
            name: ObsFunction/SIRetSymmetricMW
            options:
              siret_ch90: 1
              siret_ch150: 2
              siret_types: [ObsValue, HofX]
              bias_application: ObsValue
          a:    [0.05,   0.02,   0.01,   0.01,   0.02 ]
          b:    [0.13,   0.13,   0.14,   0.14,   0.14 ]
          err0: [500.,   500.,   2.74,   2.10,   1.55 ]
          err1: [500.,   500.,  14.57,  24.10,  32.32 ]

#  Topography check
  - filter: BlackList
    filter variables:
    - name: brightnessTemperature
      channels: *mhs_metop-b_channels
    action:
      name: inflate error
      inflation variable:
        name: ObsFunction/ObsErrorFactorTopoRad
        channels: *mhs_metop-b_channels
        options:
          sensor: mhs_metop-b
          channels: *mhs_metop-b_channels
    <<: *multiIterationFilter
#  Transmittnace Top Check
  - filter: BlackList
    filter variables:
    - name: brightnessTemperature
      channels: *mhs_metop-b_channels
    action:
      name: inflate error
      inflation variable:
        name: ObsFunction/ObsErrorFactorTransmitTopRad
        channels: *mhs_metop-b_channels
        options:
          channels: *mhs_metop-b_channels
    <<: *multiIterationFilter


#  Gross check for non-water
  - filter: Background Check
    filter variables:
    - name: brightnessTemperature
      channels: *mhs_metop-b_channels
    where:
    - variable:
        name: GeoVaLs/water_area_fraction
      maxvalue: 0.99
    function absolute threshold:
    - name: ObsFunction/ObsErrorBoundMW
      channels: *mhs_metop-b_channels
      options:
        sensor: mhs_metop-b
        channels: *mhs_metop-b_channels
        threshold: 3.0
        obserr_bound_latitude:
          name: ObsFunction/ObsErrorFactorLatRad
          options:
            latitude_parameters: [0.0, 1.0, 0.0, 1.0]
        obserr_bound_transmittop:
          name: ObsFunction/ObsErrorFactorTransmitTopRad
          channels: *mhs_metop-b_channels
          options:
            channels: *mhs_metop-b_channels
        obserr_bound_topo:
          name: ObsFunction/ObsErrorFactorTopoRad
          channels: *mhs_metop-b_channels
          options:
            channels: *mhs_metop-b_channels
            sensor: mhs_metop-b
        obserr_function:
          name: ObsFunction/ObsErrorModelRamp
          channels: *mhs_metop-b_channels
          options:
            channels: *mhs_metop-b_channels
            xvar:
              name: ObsFunction/SIRetSymmetricMW
              options:
                siret_ch90: 1
                siret_ch150: 2
                siret_types: [ObsValue, HofX]
                bias_application: HofX
            x0:    [  0.08,   0.08,   0.00,   0.00,   0.00]
            x1:    [ 27.98,  29.78,  20.70,  18.30,  14.70]
            err0:  [ 500.,   500.,    2.58,   2.60,   2.52]
            err1:  [ 500.,   500.,  16.96,  23.67,  21.70]
        obserr_bound_max: [5.0, 5.0, 10.0, 10.0, 10.0]
    action:
      name: reject
    <<: *multiIterationFilter

#  Gross check for water
  - filter: Background Check
    filter variables:
    - name: brightnessTemperature
      channels: *mhs_metop-b_channels
    where:
    - variable:
        name: GeoVaLs/water_area_fraction
      minvalue: 1.0
    function absolute threshold:
    - name: ObsFunction/ObsErrorBoundMW
      channels: *mhs_metop-b_channels
      options:
        sensor: mhs_metop-b
        channels: *mhs_metop-b_channels
        threshold: 3.0
        obserr_bound_latitude:
          name: ObsFunction/ObsErrorFactorLatRad
          options:
            latitude_parameters: [0.0, 1.0, 0.0, 1.0]
        obserr_bound_transmittop:
          name: ObsFunction/ObsErrorFactorTransmitTopRad
          channels: *mhs_metop-b_channels
          options:
            channels: *mhs_metop-b_channels
        obserr_bound_topo:
          name: ObsFunction/ObsErrorFactorTopoRad
          channels: *mhs_metop-b_channels
          options:
            channels: *mhs_metop-b_channels
            sensor: mhs_metop-b
        obserr_function:
          name: ObsFunction/ObsErrorModelQuad
          channels: *mhs_metop-b_channels
          options:
            channels: *mhs_metop-b_channels
            xvar:
              name: ObsFunction/SIRetSymmetricMW
              options:
                siret_ch90: 1
                siret_ch150: 2
                siret_types: [ObsValue, HofX]
                bias_application: HofX
            a:    [0.05,   0.02,   0.01,   0.01,   0.02 ]
            b:    [0.13,   0.13,   0.14,   0.14,   0.14 ]
            err0: [500.,   500.,   2.74,   2.10,   1.55 ]
            err1: [500.,   500.,  14.57,  24.10,  32.32 ]
        obserr_bound_max: [5.0, 5.0, 10.0, 10.0, 10.0]
    action:
      name: reject
    <<: *multiIterationFilter

#  Useflag check
  - filter: Bounds Check
    filter variables:
    - name: brightnessTemperature
      channels: *mhs_metop-b_channels
    test variables:
    - name: ObsFunction/ChannelUseflagCheckRad
      channels: *mhs_metop-b_channels
      options:
        channels: *mhs_metop-b_channels
        use_flag: [ -1, -1, 1, 1, 1]
    minvalue: 1.0e-12
    action:
      name: reject

