- obs space:
    <<: *ObsSpace
    name: SfcCorrected
    obsdatain:
      engine:
        type: H5File
        obsfile: {{InDBDir}}/sfc_obs_{{thisValidDate}}.h5
    obsdataout:
      engine:
        type: H5File
        obsfile: {{OutDBDir}}/{{obsPrefix}}_sfc.h5
    simulated variables: [stationPressure]
  obs error: *ObsErrorDiagonal
  obs operator:
    name: SfcCorrected
    correction scheme to use: UKMO   # or WRFDA
