  obs filters:
  - filter: Domain Check
    where:
    - variable:
        name: MetaData/sensorZenithAngle
      maxvalue: 60.0
    - variable:
        name: MetaData/cloudAmount
      maxvalue: 0.05 #0.0
#    - variable:
#        name: GeoVaLs/water_area_fraction
#      minvalue: 1.0
  - filter: Gaussian Thinning
    horizontal_mesh: 90.0
# Assign obsError
#std: [1.68, 1.61, 1.24]
  - filter: Perform Action
    filter variables:
    - name: [brightnessTemperature_8]
    action:
      name: assign error
      error parameter: 1.68
  - filter: Perform Action
    filter variables:
    - name: [brightnessTemperature_9]
    action:
      name: assign error
      error parameter: 1.61
  - filter: Perform Action
    filter variables:
    - name: [brightnessTemperature_10]
    action:
      name: assign error
      error parameter: 1.24
  - filter: Background Check
    threshold: 3.0
    <<: *multiIterationFilter
#  - filter: GOMsaver
#    filename: {{OutDBDir}}{{MemberDir}}/{{geoPrefix}}_abi-clr_g16.nc4
  - filter: YDIAGsaver
    filename: {{OutDBDir}}{{MemberDir}}/{{diagPrefix}}_abi-clr_g16.nc4
    filter variables:
    - name: brightness_temperature_assuming_clear_sky
      channels: *clrabi_channels
    - name: weightingfunction_of_atmosphere_layer
      channels: *clrabi_channels
    - name: pressure_level_at_peak_of_weightingfunction
      channels: *clrabi_channels
    - name: brightness_temperature_jacobian_air_temperature
      channels: *clrabi_channels
    - name: brightness_temperature_jacobian_humidity_mixing_ratio
      channels: *clrabi_channels
    - name: brightness_temperature_jacobian_surface_emissivity
      channels: *clrabi_channels
    - name: brightness_temperature_jacobian_surface_temperature
      channels: *clrabi_channels
