  obs filters:
#  Useflag check
  - filter: Bounds Check
    filter variables:
    - name: brightnessTemperature
      channels: *cris_n20_channels
    test variables:
    - name: ObsFunction/ChannelUseflagCheckRad
      channels: *cris_n20_channels
      options:
        channels: *cris_n20_channels
        use_flag: [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]
# using a subset of 89 from these 399 channels, only those where use_flag = 1
        #use_flag: [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]
# using a subset of 100 from these 399 channels, only those where use_flag = 1
#       use_flag: [-1,1,1,-1,1,-1,1,-1,1,1,1,1,1,1,-1,1,-1,1,-1,1,-1,1,-1,1,-1,1,-1,1,-1,1,-1,1,-1,1,-1,1,-1,1,-1,1,-1,1,-1,1,-1,1,-1,1,-1,1,-1,1,-1,1,-1,1,-1,1,-1,1,-1,1,-1,1,-1,-1,-1,1,-1,1,-1,1,-1,1,-1,1,-1,1,-1,1,-1,1,-1,1,-1,1,-1,1,-1,1,-1,1,-1,1,-1,1,-1,1,-1,1,-1,1,-1,1,-1,1,-1,1,-1,1,-1,1,-1,1,-1,1,-1,1,-1,1,-1,1,-1,1,-1,-1,-1,1,-1,-1,-1,1,-1,-1,-1,1,-1,-1,-1,1,-1,-1,-1,1,-1,-1,-1,1,-1,-1,-1,1,-1,-1,1,-1,-1,-1,1,-1,-1,1,-1,-1,1,-1,1,-1,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, 1,1,-1,-1,1,-1,-1,-1,1,1,1,1,-1,-1,-1,-1,1,1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1,-1,-1,1,-1,-1,-1,-1,-1,-1,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,1,-1,-1,-1,-1,-1,1,-1,-1,-1,-1,-1,-1,1,-1,-1,-1, 1,-1,-1,-1,-1,-1,-1,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, -1]
    minvalue: 1.0e-12
    action:
      name: reject
  - filter: Background Check
    threshold: 3.0
    <<: *multiIterationFilter
  #- filter: Gaussian_Thinning
  #  horizontal_mesh: {{RADTHINDISTANCE}}
  #  action:
  #    name: reduce obs space       
  #- filter: GOMsaver
  #  filename: {{OutDBDir}}/{{geoPrefix}}_cris_npp.nc4
  #- filter: YDIAGsaver
  #  filename: {{OutDBDir}}/{{diagPrefix}}_cris_npp.nc4
  #  filter variables:
  #  - name: brightness_temperature_jacobian_air_temperature
  #    channels: *cris_npp_channels
  #  - name: brightness_temperature_jacobian_humidity_mixing_ratio
  #    channels: *cris_npp_channels
  #  - name: brightness_temperature_jacobian_surface_emissivity
  #    channels: *cris_npp_channels
  #  - name: brightness_temperature_jacobian_surface_temperature
  #    channels: *cris_npp_channels
    
